<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update Cart</name>
   <tag></tag>
   <elementGuidId>6058fcc7-c114-41cc-9646-f97ff3dc5d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-updatecart-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-updatecart-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c78c02c-8d65-4ba8-bddb-71bee984dfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>81a7e315-9ec0-4bff-9614-9f9f88aaa0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update Cart</value>
      <webElementGuid>d547cba3-2feb-490d-87a4-6092bfb1a747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action primary tocart</value>
      <webElementGuid>9057fabb-7e3a-4ad1-bf51-628edd0b507a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-updatecart-button</value>
      <webElementGuid>1e01ded8-9184-44d1-87f3-fd06c5a95bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Update Cart
</value>
      <webElementGuid>557c3b32-f913-4af3-b634-696730592f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-updatecart-button&quot;)</value>
      <webElementGuid>9fcfc5a4-4f46-4922-bd37-5e7646fe3c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='product-updatecart-button']</value>
      <webElementGuid>45859b25-f496-4a80-86ff-816dafc632cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div/fieldset/div[2]/button</value>
      <webElementGuid>c0bbf0fd-4b28-41f5-93c5-4f9a3b1a5fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[2]/following::button[1]</value>
      <webElementGuid>b3ab930e-0736-4eec-9e46-27cb78051cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a required field.'])[1]/following::button[1]</value>
      <webElementGuid>47558493-a6ca-4367-93b0-53f0c5b3c890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Wish List'])[1]/preceding::button[1]</value>
      <webElementGuid>aa1ec40a-c14e-4034-8910-2d4c15a81867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/button</value>
      <webElementGuid>02db1895-5ffc-4447-9dd2-8f4aec1a4fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Update Cart' and @id = 'product-updatecart-button' and (text() = '
Update Cart
' or . = '
Update Cart
')]</value>
      <webElementGuid>b50cab52-e103-4688-9947-38f6d81f90e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
