<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_M</name>
   <tag></tag>
   <elementGuidId>7d1d3391-b9e3-4b24-a42a-75c53144c900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='option-label-size-143-item-168']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#option-label-size-143-item-168</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c765502-c4c6-4a7b-952c-6f798493a21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option text</value>
      <webElementGuid>99240503-97fd-48a8-b99c-310145d8fea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-143-item-168</value>
      <webElementGuid>3c847b07-479b-467a-8d9e-6a6dc03cc481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>aa0c1d25-b1d8-4c2f-be2d-928fdc484311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2debddc7-900f-4e57-8b02-1dc23bace363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-size-143</value>
      <webElementGuid>75513be6-920a-4d72-bf70-1f3266585fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c22ce052-b141-4eef-9df9-776e10e611ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ef131fc-bc9b-494c-bd3a-4747e3794c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>168</value>
      <webElementGuid>5b9ab985-5a52-4d5f-8c13-68850c90d85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>3727f939-b675-40d3-bd9b-f99d891e940e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>2faed9dd-8d0c-4f4b-ab01-d905d2e675ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>302ca2e7-2584-4569-a687-746acbe0508e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>80d604c1-674e-44ce-8689-1bc8d3c9564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>8a3f5274-80b5-4c90-a859-f51ec32b3d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>963238c3-cb8c-427a-bcf5-07cc675a3737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>e6ebd8b0-7672-414e-bf25-ff4ac69486d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-size-143-item-168&quot;)</value>
      <webElementGuid>97e07a25-ec49-4297-893c-1295d7c9f737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-size-143-item-168']</value>
      <webElementGuid>1fafef93-9b46-427e-85f0-024818dda3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div/div[3]</value>
      <webElementGuid>dd86c863-76ef-4ad1-b6e9-f7ca3f717f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::div[1]</value>
      <webElementGuid>813878fd-4f28-475f-b0d5-6d5c34e3dabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XS'])[1]/following::div[2]</value>
      <webElementGuid>3e084107-c4e8-4341-8daf-0299a0d947c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[2]/preceding::div[1]</value>
      <webElementGuid>fe3b993c-6fd5-4b43-9a63-a924c1f67dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/preceding::div[2]</value>
      <webElementGuid>5cb44331-c76e-4bbb-ac76-5bb376049ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='M']/parent::*</value>
      <webElementGuid>0b3a6022-3c14-4a7f-9aaf-efa426c336c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[3]</value>
      <webElementGuid>b573c44d-c681-41a5-a6c0-3cd70fbd9696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-size-143-item-168' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>50b39d0d-2118-4a91-9118-4b15c06af5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
