<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_watch, T-shirt181</name>
   <tag></tag>
   <elementGuidId>83925072-9deb-4cdd-b56a-28fb577a0e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qs-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='qs-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fbea9a7d-c23c-47ee-b940-bafb7a7c32d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>6afe5906-861b-4f84-abe8-e1c6a6e6c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qs-option-1</value>
      <webElementGuid>94314d12-15d2-4de0-bc62-1407ec0a4de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5918b1a4-d9f7-449f-aca1-df43df66b1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> watch, T-shirt181</value>
      <webElementGuid>f7266e53-5a29-4e8c-9230-f7582d52b77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qs-option-1&quot;)</value>
      <webElementGuid>e6d964ab-ce6b-4aa4-b784-8524f44bbe43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='qs-option-1']</value>
      <webElementGuid>448f75b4-ad66-4b63-8455-adfc4cbb61e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_autocomplete']/ul/li[2]</value>
      <webElementGuid>8f987260-c2c0-489b-8124-5b0e9e2cc4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='watch'])[1]/following::li[1]</value>
      <webElementGuid>c5d7a363-e5a0-487d-a738-5b2c7c8e6e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::li[2]</value>
      <webElementGuid>e68e6fca-6581-4644-a560-221f71ed6906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='watch, jump rope'])[1]/preceding::li[1]</value>
      <webElementGuid>4fc1b267-2913-48c7-9441-a25b8e8fafa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]</value>
      <webElementGuid>93601179-aa57-405c-a67f-da3d3e11ae37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'qs-option-1' and (text() = ' watch, T-shirt181' or . = ' watch, T-shirt181')]</value>
      <webElementGuid>bb390f98-495c-48b5-a221-9693405f468e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
