<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color_option-label-color-93-item-57</name>
   <tag></tag>
   <elementGuidId>34e6fc4d-11a2-45e2-97d8-8377a039f7d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-label-color-93-item-57</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='option-label-color-93-item-57']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bb26140-fc2f-44c7-af18-b395a3046ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color</value>
      <webElementGuid>805c957a-b7b4-46cc-8695-67fec8407f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-color-93-item-57</value>
      <webElementGuid>ff5215d6-9852-45bf-abb8-49ad7eb7b296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>65f20706-0f74-4e1c-9b66-c09750730202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4156f604-b47f-44e1-b72d-66a2095f4df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-color-93</value>
      <webElementGuid>77b3c14a-cd99-41ff-8c9f-234d53fb0165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5db9fba0-ece1-47c5-9ad0-491a91f94f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cc255402-e0b4-4db6-b6e1-507c671bf2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>57</value>
      <webElementGuid>c9767fa6-c9fa-4dc5-8ede-7ffbfea801ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>Purple</value>
      <webElementGuid>650a5278-0c5b-49c6-8594-2efd8f97bf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Purple</value>
      <webElementGuid>d67d6d3e-2fa4-4dd3-b110-9a2554fb3643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>#ef3dff</value>
      <webElementGuid>f052439d-6a3e-4a9b-a97b-02d5f09027be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c0e57a99-d2aa-4a87-b5ca-261e0340fbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>069f3ded-a5f5-4cfc-a6b4-c491035ed906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>23dab92a-5cfc-400a-a199-ec0253405131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-color-93-item-57&quot;)</value>
      <webElementGuid>0f5924cb-2a74-451d-8025-c2b3df6d36c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-color-93-item-57']</value>
      <webElementGuid>9148f08d-3f66-4ca0-b698-f96eb720119a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div[2]/div/div[3]</value>
      <webElementGuid>8f62b768-9ea5-4c15-b5da-26a117ec3bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>f289e1d3-f49d-4809-85c6-0399f4fc2ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-color-93-item-57']</value>
      <webElementGuid>f65df1aa-ddb2-49b3-a46b-d71fb3605c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
