<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_telephone</name>
   <tag></tag>
   <elementGuidId>a50ff5ae-62bb-4921-8409-1c4ee10b6fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ec12786-f630-425a-b18c-2b57b4a45078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>5886b0e7-bbb8-4899-9bcb-6a50f0317b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>84044aa8-9718-4570-9e32-54c526a12976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>bca7c2b6-7492-411f-9b0d-47f354deeb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>42a6cd73-2292-42eb-9263-2e5516860eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6feea5e-e8a7-4c56-a3e5-3fd96f4b31e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telephone&quot;)</value>
      <webElementGuid>066895b4-89ff-4a24-809a-5d0e545aca28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telephone']</value>
      <webElementGuid>89d92cc9-ac92-43ba-aa40-79a189b4fecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/fieldset/div[4]/div/input</value>
      <webElementGuid>5c92abd4-a203-48ee-b863-b055c364a512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>416834db-9644-4e86-8d01-6dd5e2aecd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'telephone' and @id = 'telephone' and @title = 'Phone Number' and @type = 'text']</value>
      <webElementGuid>d2c411b4-9127-4557-bde4-2b40ff47b5e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
