<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01_verify_login_logout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5b0bf8f4-f161-41fe-8614-e4502c00ce85</testSuiteGuid>
   <testCaseLink>
      <guid>741a8ad2-d63b-4633-87d4-f020e62c7875</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/user_account_actions/login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>36e669f6-b81f-4d99-bb8a-a1fd0e9f8e47</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>36e669f6-b81f-4d99-bb8a-a1fd0e9f8e47</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>708a5310-2e53-44c3-9b8d-bffbaadb1da0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>36e669f6-b81f-4d99-bb8a-a1fd0e9f8e47</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>abeff59c-ccf9-453a-83bc-fb8401fa09f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1edb4f5c-8ab0-4270-b412-068fb99039b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/user_account_actions/logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
